import { useMemo, type Dispatch, type SetStateAction } from 'react';
import type { AppData, RothTransfer, Scenario } from '../domain/types';
import { applyScenarioOverrides, projectCore } from '../domain/calculations';
import { isMegaBackdoor, rothTransferError } from '../domain/roth';
import { Field, SelectField, money } from './ui';

export function RothEditor({ data, setData, scenario }: { data: AppData; setData: Dispatch<SetStateAction<AppData>>; scenario: Scenario }) {
  const effective = useMemo(() => applyScenarioOverrides(data, scenario), [data, scenario]);
  const transfers = effective.profile.rothTransfers ?? [];
  const events = useMemo(() => projectCore({ ...effective, includeRetirement: true }).flatMap((point) => point.rothTransfers), [effective]);
  const save = (next: RothTransfer[]) => setData((old) => ({ ...old, scenarios: old.scenarios.map((item) => item.id === scenario.id ? { ...item, overrides: { ...item.overrides, rothTransfers: next } } : item) }));
  const update = (id: string, patch: Partial<RothTransfer>) => save(transfers.map((item) => item.id === id ? { ...item, ...patch } : item));
  const destinations = data.accounts.filter((account) => account.type === 'Roth IRA');
  const taxAccounts = data.accounts.filter((account) => ['HYSA / Cash', 'Taxable Brokerage'].includes(account.type) && account.accessibility === 'Immediate');
  const history = data.profile.rothConversionHistory ?? [];
  const saveHistory = (next: typeof history) => setData((old) => ({ ...old, profile: { ...old.profile, rothConversionHistory: next } }));
  return <details className="advanced-inputs roth-editor"><summary>Roth conversions, backdoors & rollovers</summary><div className="editor-stack">
    <p className="muted">Schedule transfers for <strong>{scenario.name}</strong>. Money moves between accounts; it is not counted as a new contribution. Choose a one-time, monthly, or annual schedule.</p>
    <p className="muted">For a backdoor Roth, enter the contribution to your Traditional IRA in Monthly money, then schedule its conversion here. Do not also enter it as a Roth IRA contribution. Transfers happen at the start of the selected month, before that month’s contributions and withdrawals.</p>
    <p className="muted">For a mega backdoor, use a separate After-tax 401(k) account for the plan’s after-tax subaccount. Enter its current contribution basis in account details and future employee contributions in Monthly money. These are payroll deductions already excluded from deposited pay. Keep employer contributions in their actual pretax or Roth account, and do not duplicate balances or contributions across subaccounts.</p>
    <p className="muted">Your employer plan must permit after-tax contributions and the chosen rollover or in-plan conversion. Transfers use the after-tax subaccount’s proportional basis and earnings; confirm that your plan separately accounts for that source. Annual contribution limits and plan eligibility are not checked.</p>
    <button className="button secondary" onClick={() => setData((old) => {
      const account = { id: crypto.randomUUID(), name: 'After-tax 401(k)', type: 'After-tax 401(k)' as const, balance: 0, afterTaxBasis: 0, monthlyContribution: 0, employerContribution: 0, fireEligible: true, includeInNetWorth: true, taxTreatment: 'Other' as const, accessibility: 'Restricted' as const, notes: '', holdings: [] };
      return { ...old, accounts: [...old.accounts, account], phases: old.phases.map((phase) => ({ ...phase, contributions: { ...phase.contributions, [account.id]: { personal: 0, employer: 0 } } })) };
    })}>Add after-tax 401(k) account</button>
    {transfers.map((transfer, index) => {
      const mega = isMegaBackdoor(transfer);
      const destinationsForTransfer = transfer.kind === 'mega-plan' ? data.accounts.filter((account) => account.type === 'Roth 401(k)') : destinations;
      const sources = data.accounts.filter((account) => mega ? account.type === 'After-tax 401(k)' : transfer.kind === 'roth401k' ? account.type === 'Roth 401(k)' : transfer.kind === 'backdoor' ? account.type === 'Traditional IRA' : ['Traditional IRA', 'Traditional 401(k)'].includes(account.type));
      const transferEvents = events.filter((item) => item.id === transfer.id);
      const event = transferEvents[0];
      const error = rothTransferError(transfer, data.accounts) ?? (transfer.age < effective.profile.currentAge || transfer.age > effective.profile.maxAge ? 'Transfer age must be within this scenario’s projection.' : undefined);
      return <div className="roth-transfer" key={transfer.id}><h3>Transfer {index + 1}</h3><div className="editor-grid">
        <SelectField label="Transfer type" value={transfer.kind} onChange={(value) => update(transfer.id, { kind: value as RothTransfer['kind'], sourceId: '', destinationId: '', basis: 0, fullBalance: false, earningsDestinationId: undefined })}><option value="conversion">Traditional IRA / 401(k) → Roth IRA</option><option value="backdoor">Backdoor Roth IRA</option><option value="roth401k">Roth 401(k) → Roth IRA</option><option value="mega-ira">Mega backdoor → Roth IRA</option><option value="mega-plan">Mega backdoor → Roth 401(k) (in-plan)</option></SelectField>
        <Field label="Transfer age" value={transfer.age} min={effective.profile.currentAge} max={effective.profile.maxAge} step={1 / 12} onChange={(age) => update(transfer.id, { age })} hint="Rounded to the nearest projection month. Amounts use the selected projection dollar mode." />
        <SelectField label="Transfer from" value={transfer.sourceId} onChange={(sourceId) => update(transfer.id, { sourceId })}><option value="">Choose source</option>{sources.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</SelectField>
        <SelectField label={transfer.kind === 'mega-plan' ? 'Transfer to Roth 401(k)' : 'Transfer to Roth IRA'} value={transfer.destinationId} onChange={(destinationId) => update(transfer.id, { destinationId })}><option value="">Choose Roth destination</option>{destinationsForTransfer.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</SelectField>
        <SelectField label="Repeat transfer" value={transfer.repeat ?? 'once'} onChange={(repeat) => update(transfer.id, { repeat: repeat as RothTransfer['repeat'], endAge: transfer.endAge ?? effective.profile.retirementAge })}><option value="once">Once</option><option value="monthly">Monthly</option><option value="annual">Annually</option></SelectField>
        {transfer.repeat && transfer.repeat !== 'once' && <Field label="Last transfer age" value={transfer.endAge ?? transfer.age} min={transfer.age} max={effective.profile.maxAge} step={1 / 12} onChange={(endAge) => update(transfer.id, { endAge })} />}
        {mega && <SelectField label="Transfer sizing" value={transfer.fullBalance ? 'all' : 'fixed'} onChange={(value) => update(transfer.id, { fullBalance: value === 'all' })}><option value="fixed">Fixed amount per transfer</option><option value="all">Sweep available balance</option></SelectField>}
        {!(mega && transfer.fullBalance) && <Field label="Transfer amount" value={transfer.amount} prefix="$" min={0} onChange={(amount) => update(transfer.id, { amount, basis: Math.min(transfer.basis, amount) })} />}
        {!mega && <Field label={transfer.kind === 'roth401k' ? 'Rollover contribution basis' : 'Verified nontaxable portion'} value={transfer.basis} prefix="$" min={0} max={transfer.amount} onChange={(basis) => update(transfer.id, { basis })} hint={transfer.kind === 'roth401k' ? 'For a nonqualified rollover, enter the contribution portion, excluding earnings. For a qualified rollover, the entire amount may count as basis; verify before entering.' : 'Enter the nontaxable amount after applying the IRA pro-rata rule, not just the nondeductible contribution. Defaults to zero; the app does not calculate Form 8606.'} />}
        {transfer.kind === 'mega-ira' && <SelectField label="Treatment of pretax earnings" value={transfer.earningsDestinationId ?? ''} onChange={(earningsDestinationId) => update(transfer.id, { earningsDestinationId: earningsDestinationId || undefined })}><option value="">Convert earnings to Roth (taxable)</option>{data.accounts.filter((account) => account.type === 'Traditional IRA').map((account) => <option key={account.id} value={account.id}>Roll earnings to {account.name} (tax deferred)</option>)}</SelectField>}
        {transfer.kind !== 'roth401k' && !transfer.earningsDestinationId && <><Field label="Estimated conversion tax rate" value={transfer.taxRate * 100} suffix="%" min={0} max={100} step={0.1} onChange={(rate) => update(transfer.id, { taxRate: rate / 100 })} hint="Combined estimated federal and state rate, applied only to the taxable portion. No tax-bracket or income calculation is performed." /><SelectField label="Pay conversion tax from" value={transfer.taxAccountId} onChange={(taxAccountId) => update(transfer.id, { taxAccountId })}><option value="">Choose cash / brokerage</option>{taxAccounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</SelectField></>}
      </div>
      {error ? <p className="negative-text" role="alert">{error} This transfer is not applied.</p> : event && <p className="muted">{event.date.slice(0, 7)}: {money(event.transferred)} transferred · {money(event.taxable)} taxable · estimated tax {money(event.tax)} ({money(event.taxPaid)} funded). {transfer.kind === 'mega-plan' ? 'This remains a restricted plan balance; it does not add accessible Roth IRA basis.' : event.accessYear ? `Taxable conversion principal clears its five-tax-year clock January 1, ${event.accessYear}, or at age 59½. Earlier conversions can affect access.` : 'Basis access still follows Roth IRA withdrawal ordering.'}</p>}
      {mega && event && !error && <p className="muted">First transfer: {money(event.nontaxable ?? 0)} after-tax principal · {money(event.rothAmount ?? 0)} to Roth · {money(event.pretaxRollover ?? 0)} earnings to Traditional IRA. Basis is calculated from the source account rather than entered per transfer.</p>}
      {transferEvents.length > 1 && <p className="muted">{transferEvents.length} projected transfers through {transferEvents.at(-1)!.date.slice(0, 7)} · {money(transferEvents.reduce((sum, item) => sum + item.transferred, 0))} moved · {money(transferEvents.reduce((sum, item) => sum + item.tax, 0))} estimated tax · {money(transferEvents.reduce((sum, item) => sum + item.taxPaid, 0))} funded.</p>}
      {!error && [...new Set(transferEvents.flatMap((item) => item.warning ? [item.warning] : []))].map((warning) => <p key={warning} className="negative-text" role="alert">{warning}</p>)}
      {!error && !event && <p className="muted">No transfers projected: the source has no available balance on the scheduled dates.</p>}
      {transfer.kind === 'mega-plan' && <p className="fine-print">Use the Roth 401(k) subaccount in the same employer plan. A subsequent Roth IRA rollover within five tax years of a taxable in-plan conversion, while under 59½, is not modeled and will be skipped with a warning. Direct mega-backdoor transfers to a Roth IRA use the IRA conversion-basis tracker.</p>}
      <button className="text-button danger" onClick={() => save(transfers.filter((item) => item.id !== transfer.id))}>Remove transfer {index + 1}</button></div>;
    })}
    <button className="add-card" onClick={() => save([...transfers, { id: crypto.randomUUID(), kind: 'conversion', age: effective.profile.currentAge, sourceId: '', destinationId: destinations[0]?.id ?? '', amount: 0, basis: 0, taxRate: 0.22, taxAccountId: taxAccounts[0]?.id ?? '' }])}>Add Roth transfer</button>
    <details><summary>Existing conversion basis · shared across scenarios</summary><p className="muted">Enter remaining, unwithdrawn conversion principal by original tax year. These amounts must already be included in current Roth IRA balances. They do not move money or add wealth. Keep regular contribution basis in Plan separate.</p>
      {history.map((lot, index) => <div className="roth-transfer" key={index}><div className="editor-grid"><Field label="Original conversion year" value={lot.year} min={1998} max={new Date().getFullYear()} onChange={(year) => saveHistory(history.map((item, i) => i === index ? { ...item, year: Math.round(year) } : item))} /><Field label="Remaining originally taxable principal" value={lot.taxable} prefix="$" min={0} onChange={(taxable) => saveHistory(history.map((item, i) => i === index ? { ...item, taxable } : item))} /><Field label="Remaining nontaxable principal" value={lot.nontaxable} prefix="$" min={0} onChange={(nontaxable) => saveHistory(history.map((item, i) => i === index ? { ...item, nontaxable } : item))} /></div><button className="text-button danger" onClick={() => saveHistory(history.filter((_, i) => i !== index))}>Remove history entry {index + 1}</button></div>)}
      <button className="add-card" onClick={() => saveHistory([...history, { year: new Date().getFullYear() - 5, taxable: 0, nontaxable: 0 }])}>Add existing conversion basis</button>
    </details>
    <p className="fine-print">Planning assumptions: direct rollovers, no withholding, and conversion tax paid immediately from the selected account. An underfunded tax payment is flagged, not silently funded elsewhere. IRA pro-rata calculations must include all applicable traditional, SEP, and SIMPLE IRAs and year-end balances. Contribution limits, plan eligibility, required distributions, capital-gains tax on tax-funding sales, and employer-specific distribution rules are not validated. Monthly budget totals exclude scheduled transfers and their tax payments.</p>
    <p className="fine-print">Bridge access includes regular basis and conversion principal available under withdrawal ordering; earnings qualification is not modeled. Retirement drawdown still withdraws proportionally across FIRE accounts and does not enforce penalty-free access or calculate early-withdrawal penalties.</p>
    <p className="fine-print">Rules reference: <a href="https://www.irs.gov/retirement-plans/rollovers-of-after-tax-contributions-in-retirement-plans" target="_blank" rel="noreferrer">After-tax plan rollovers</a> · <a href="https://www.irs.gov/publications/p590b" target="_blank" rel="noreferrer">IRS Publication 590-B</a> · <a href="https://www.irs.gov/instructions/i8606" target="_blank" rel="noreferrer">Form 8606</a> · <a href="https://www.irs.gov/retirement-plans/retirement-plans-faqs-on-designated-roth-accounts" target="_blank" rel="noreferrer">Roth plan rollovers</a></p>
  </div></details>;
}
